POST http://localhost:5000/song/create
Content-Type: application/json

{
   
"title":"Bohemian Rhapsody",
"artist":"Queen",
"album":"A Night at The Opera",
"genre":"Rock"
}
###

GET http://localhost:5000/song/allSongs
###

PUT http://localhost:5000/song/66cf309c08185ccf3e13fd65
Content-Type: application/json

{
    "title":"Jah"
}
###

DELETE http://localhost:5000/song/66cf4b4140935c857343f331
###

GET http://localhost:5000/song/statistics